/*DESHABILITAR RESTRICCIONES*/
EXEC SYS.SP_MSFOREACHTABLE 'ALTER TABLE ? NOCHECK CONSTRAIN ALL'
GO

EXEC SYS.SP_MSFOREACHTABLE 'ALTER TABLE ? DISABLE TRIGGER ALL'
GO

EXEC SYS.SP_MSFOREACHTABLE
	'	BEGIN TRY
			SET QUOTED_IDENTIFIER ON
			TRUNCATE TABLE ?
		END TRY
		BEGIN CATCH
			DELETE FROM ?
		END CATCH;'
GO